//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace Proxy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.IReceiveData")]
    public interface IReceiveData {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IReceiveData/ReceiveData", ReplyAction="urn:IReceiveData/ReceiveDataResponse")]
        System.IAsyncResult BeginReceiveData(Proxy.ServiceReference1.ReceiveDataRequest request, System.AsyncCallback callback, object asyncState);
        
        Proxy.ServiceReference1.ReceiveDataResponse EndReceiveData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IReceiveData/ReceivePoint", ReplyAction="urn:IReceiveData/ReceivePointResponse")]
        System.IAsyncResult BeginReceivePoint(Proxy.ServiceReference1.ReceivePointRequest request, System.AsyncCallback callback, object asyncState);
        
        Proxy.ServiceReference1.ReceivePointResponse EndReceivePoint(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IReceiveData/ReceivePoints", ReplyAction="urn:IReceiveData/ReceivePointsResponse")]
        System.IAsyncResult BeginReceivePoints(Proxy.ServiceReference1.ReceivePointsRequest request, System.AsyncCallback callback, object asyncState);
        
        Proxy.ServiceReference1.ReceivePointsResponse EndReceivePoints(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveData", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceiveDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] data;
        
        public ReceiveDataRequest() {
        }
        
        public ReceiveDataRequest(byte[] data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveDataResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceiveDataResponse {
        
        public ReceiveDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceivePoint", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceivePointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double y;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public double z;
        
        public ReceivePointRequest() {
        }
        
        public ReceivePointRequest(double x, double y, double z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceivePointResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceivePointResponse {
        
        public ReceivePointResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceivePoints", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceivePointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double[] xs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double[] ys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public double[] zs;
        
        public ReceivePointsRequest() {
        }
        
        public ReceivePointsRequest(double[] xs, double[] ys, double[] zs) {
            this.xs = xs;
            this.ys = ys;
            this.zs = zs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceivePointsResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class ReceivePointsResponse {
        
        public ReceivePointsResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiveDataChannel : Proxy.ServiceReference1.IReceiveData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReceiveDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Proxy.ServiceReference1.ReceiveDataResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Proxy.ServiceReference1.ReceiveDataResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceivePointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReceivePointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Proxy.ServiceReference1.ReceivePointResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Proxy.ServiceReference1.ReceivePointResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceivePointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReceivePointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Proxy.ServiceReference1.ReceivePointsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Proxy.ServiceReference1.ReceivePointsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveDataClient : System.ServiceModel.ClientBase<Proxy.ServiceReference1.IReceiveData>, Proxy.ServiceReference1.IReceiveData {
        
        private BeginOperationDelegate onBeginReceiveDataDelegate;
        
        private EndOperationDelegate onEndReceiveDataDelegate;
        
        private System.Threading.SendOrPostCallback onReceiveDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginReceivePointDelegate;
        
        private EndOperationDelegate onEndReceivePointDelegate;
        
        private System.Threading.SendOrPostCallback onReceivePointCompletedDelegate;
        
        private BeginOperationDelegate onBeginReceivePointsDelegate;
        
        private EndOperationDelegate onEndReceivePointsDelegate;
        
        private System.Threading.SendOrPostCallback onReceivePointsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ReceiveDataClient() {
        }
        
        public ReceiveDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ReceiveDataCompletedEventArgs> ReceiveDataCompleted;
        
        public event System.EventHandler<ReceivePointCompletedEventArgs> ReceivePointCompleted;
        
        public event System.EventHandler<ReceivePointsCompletedEventArgs> ReceivePointsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proxy.ServiceReference1.IReceiveData.BeginReceiveData(Proxy.ServiceReference1.ReceiveDataRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReceiveData(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proxy.ServiceReference1.ReceiveDataResponse Proxy.ServiceReference1.IReceiveData.EndReceiveData(System.IAsyncResult result) {
            return base.Channel.EndReceiveData(result);
        }
        
        private System.IAsyncResult OnBeginReceiveData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Proxy.ServiceReference1.ReceiveDataRequest request = ((Proxy.ServiceReference1.ReceiveDataRequest)(inValues[0]));
            return ((Proxy.ServiceReference1.IReceiveData)(this)).BeginReceiveData(request, callback, asyncState);
        }
        
        private object[] OnEndReceiveData(System.IAsyncResult result) {
            Proxy.ServiceReference1.ReceiveDataResponse retVal = ((Proxy.ServiceReference1.IReceiveData)(this)).EndReceiveData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReceiveDataCompleted(object state) {
            if ((this.ReceiveDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReceiveDataCompleted(this, new ReceiveDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReceiveDataAsync(Proxy.ServiceReference1.ReceiveDataRequest request) {
            this.ReceiveDataAsync(request, null);
        }
        
        public void ReceiveDataAsync(Proxy.ServiceReference1.ReceiveDataRequest request, object userState) {
            if ((this.onBeginReceiveDataDelegate == null)) {
                this.onBeginReceiveDataDelegate = new BeginOperationDelegate(this.OnBeginReceiveData);
            }
            if ((this.onEndReceiveDataDelegate == null)) {
                this.onEndReceiveDataDelegate = new EndOperationDelegate(this.OnEndReceiveData);
            }
            if ((this.onReceiveDataCompletedDelegate == null)) {
                this.onReceiveDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceiveDataCompleted);
            }
            base.InvokeAsync(this.onBeginReceiveDataDelegate, new object[] {
                        request}, this.onEndReceiveDataDelegate, this.onReceiveDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proxy.ServiceReference1.IReceiveData.BeginReceivePoint(Proxy.ServiceReference1.ReceivePointRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReceivePoint(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proxy.ServiceReference1.ReceivePointResponse Proxy.ServiceReference1.IReceiveData.EndReceivePoint(System.IAsyncResult result) {
            return base.Channel.EndReceivePoint(result);
        }
        
        private System.IAsyncResult OnBeginReceivePoint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Proxy.ServiceReference1.ReceivePointRequest request = ((Proxy.ServiceReference1.ReceivePointRequest)(inValues[0]));
            return ((Proxy.ServiceReference1.IReceiveData)(this)).BeginReceivePoint(request, callback, asyncState);
        }
        
        private object[] OnEndReceivePoint(System.IAsyncResult result) {
            Proxy.ServiceReference1.ReceivePointResponse retVal = ((Proxy.ServiceReference1.IReceiveData)(this)).EndReceivePoint(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReceivePointCompleted(object state) {
            if ((this.ReceivePointCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReceivePointCompleted(this, new ReceivePointCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReceivePointAsync(Proxy.ServiceReference1.ReceivePointRequest request) {
            this.ReceivePointAsync(request, null);
        }
        
        public void ReceivePointAsync(Proxy.ServiceReference1.ReceivePointRequest request, object userState) {
            if ((this.onBeginReceivePointDelegate == null)) {
                this.onBeginReceivePointDelegate = new BeginOperationDelegate(this.OnBeginReceivePoint);
            }
            if ((this.onEndReceivePointDelegate == null)) {
                this.onEndReceivePointDelegate = new EndOperationDelegate(this.OnEndReceivePoint);
            }
            if ((this.onReceivePointCompletedDelegate == null)) {
                this.onReceivePointCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceivePointCompleted);
            }
            base.InvokeAsync(this.onBeginReceivePointDelegate, new object[] {
                        request}, this.onEndReceivePointDelegate, this.onReceivePointCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proxy.ServiceReference1.IReceiveData.BeginReceivePoints(Proxy.ServiceReference1.ReceivePointsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReceivePoints(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proxy.ServiceReference1.ReceivePointsResponse Proxy.ServiceReference1.IReceiveData.EndReceivePoints(System.IAsyncResult result) {
            return base.Channel.EndReceivePoints(result);
        }
        
        private System.IAsyncResult OnBeginReceivePoints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Proxy.ServiceReference1.ReceivePointsRequest request = ((Proxy.ServiceReference1.ReceivePointsRequest)(inValues[0]));
            return ((Proxy.ServiceReference1.IReceiveData)(this)).BeginReceivePoints(request, callback, asyncState);
        }
        
        private object[] OnEndReceivePoints(System.IAsyncResult result) {
            Proxy.ServiceReference1.ReceivePointsResponse retVal = ((Proxy.ServiceReference1.IReceiveData)(this)).EndReceivePoints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReceivePointsCompleted(object state) {
            if ((this.ReceivePointsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReceivePointsCompleted(this, new ReceivePointsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReceivePointsAsync(Proxy.ServiceReference1.ReceivePointsRequest request) {
            this.ReceivePointsAsync(request, null);
        }
        
        public void ReceivePointsAsync(Proxy.ServiceReference1.ReceivePointsRequest request, object userState) {
            if ((this.onBeginReceivePointsDelegate == null)) {
                this.onBeginReceivePointsDelegate = new BeginOperationDelegate(this.OnBeginReceivePoints);
            }
            if ((this.onEndReceivePointsDelegate == null)) {
                this.onEndReceivePointsDelegate = new EndOperationDelegate(this.OnEndReceivePoints);
            }
            if ((this.onReceivePointsCompletedDelegate == null)) {
                this.onReceivePointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceivePointsCompleted);
            }
            base.InvokeAsync(this.onBeginReceivePointsDelegate, new object[] {
                        request}, this.onEndReceivePointsDelegate, this.onReceivePointsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Proxy.ServiceReference1.IReceiveData CreateChannel() {
            return new ReceiveDataClientChannel(this);
        }
        
        private class ReceiveDataClientChannel : ChannelBase<Proxy.ServiceReference1.IReceiveData>, Proxy.ServiceReference1.IReceiveData {
            
            public ReceiveDataClientChannel(System.ServiceModel.ClientBase<Proxy.ServiceReference1.IReceiveData> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginReceiveData(Proxy.ServiceReference1.ReceiveDataRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ReceiveData", _args, callback, asyncState);
                return _result;
            }
            
            public Proxy.ServiceReference1.ReceiveDataResponse EndReceiveData(System.IAsyncResult result) {
                object[] _args = new object[0];
                Proxy.ServiceReference1.ReceiveDataResponse _result = ((Proxy.ServiceReference1.ReceiveDataResponse)(base.EndInvoke("ReceiveData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReceivePoint(Proxy.ServiceReference1.ReceivePointRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ReceivePoint", _args, callback, asyncState);
                return _result;
            }
            
            public Proxy.ServiceReference1.ReceivePointResponse EndReceivePoint(System.IAsyncResult result) {
                object[] _args = new object[0];
                Proxy.ServiceReference1.ReceivePointResponse _result = ((Proxy.ServiceReference1.ReceivePointResponse)(base.EndInvoke("ReceivePoint", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReceivePoints(Proxy.ServiceReference1.ReceivePointsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ReceivePoints", _args, callback, asyncState);
                return _result;
            }
            
            public Proxy.ServiceReference1.ReceivePointsResponse EndReceivePoints(System.IAsyncResult result) {
                object[] _args = new object[0];
                Proxy.ServiceReference1.ReceivePointsResponse _result = ((Proxy.ServiceReference1.ReceivePointsResponse)(base.EndInvoke("ReceivePoints", _args, result)));
                return _result;
            }
        }
    }
}
