//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace System
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TupleOfdoubledoubledouble", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfdoubledoubledouble : object
    {
        
        private double m_Item1Field;
        
        private double m_Item2Field;
        
        private double m_Item3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double m_Item1
        {
            get
            {
                return this.m_Item1Field;
            }
            set
            {
                this.m_Item1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double m_Item2
        {
            get
            {
                return this.m_Item2Field;
            }
            set
            {
                this.m_Item2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double m_Item3
        {
            get
            {
                return this.m_Item3Field;
            }
            set
            {
                this.m_Item3Field = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IReceiveData")]
public interface IReceiveData
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReceiveData/ReceiveData", ReplyAction="http://tempuri.org/IReceiveData/ReceiveDataResponse")]
    System.IAsyncResult BeginReceiveData(byte[] data, System.AsyncCallback callback, object asyncState);
    
    void EndReceiveData(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReceiveData/ReceivePoint", ReplyAction="http://tempuri.org/IReceiveData/ReceivePointResponse")]
    System.IAsyncResult BeginReceivePoint(System.TupleOfdoubledoubledouble data, System.AsyncCallback callback, object asyncState);
    
    void EndReceivePoint(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReceiveData/ReceivePoints", ReplyAction="http://tempuri.org/IReceiveData/ReceivePointsResponse")]
    System.IAsyncResult BeginReceivePoints(System.TupleOfdoubledoubledouble[] data, System.AsyncCallback callback, object asyncState);
    
    void EndReceivePoints(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IReceiveDataChannel : IReceiveData, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ReceiveDataClient : System.ServiceModel.ClientBase<IReceiveData>, IReceiveData
{
    
    private BeginOperationDelegate onBeginReceiveDataDelegate;
    
    private EndOperationDelegate onEndReceiveDataDelegate;
    
    private System.Threading.SendOrPostCallback onReceiveDataCompletedDelegate;
    
    private BeginOperationDelegate onBeginReceivePointDelegate;
    
    private EndOperationDelegate onEndReceivePointDelegate;
    
    private System.Threading.SendOrPostCallback onReceivePointCompletedDelegate;
    
    private BeginOperationDelegate onBeginReceivePointsDelegate;
    
    private EndOperationDelegate onEndReceivePointsDelegate;
    
    private System.Threading.SendOrPostCallback onReceivePointsCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public ReceiveDataClient()
    {
    }
    
    public ReceiveDataClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ReceiveDataClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReceiveDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReceiveDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReceiveDataCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReceivePointCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReceivePointsCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IReceiveData.BeginReceiveData(byte[] data, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginReceiveData(data, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IReceiveData.EndReceiveData(System.IAsyncResult result)
    {
        base.Channel.EndReceiveData(result);
    }
    
    private System.IAsyncResult OnBeginReceiveData(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        byte[] data = ((byte[])(inValues[0]));
        return ((IReceiveData)(this)).BeginReceiveData(data, callback, asyncState);
    }
    
    private object[] OnEndReceiveData(System.IAsyncResult result)
    {
        ((IReceiveData)(this)).EndReceiveData(result);
        return null;
    }
    
    private void OnReceiveDataCompleted(object state)
    {
        if ((this.ReceiveDataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ReceiveDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ReceiveDataAsync(byte[] data)
    {
        this.ReceiveDataAsync(data, null);
    }
    
    public void ReceiveDataAsync(byte[] data, object userState)
    {
        if ((this.onBeginReceiveDataDelegate == null))
        {
            this.onBeginReceiveDataDelegate = new BeginOperationDelegate(this.OnBeginReceiveData);
        }
        if ((this.onEndReceiveDataDelegate == null))
        {
            this.onEndReceiveDataDelegate = new EndOperationDelegate(this.OnEndReceiveData);
        }
        if ((this.onReceiveDataCompletedDelegate == null))
        {
            this.onReceiveDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceiveDataCompleted);
        }
        base.InvokeAsync(this.onBeginReceiveDataDelegate, new object[] {
                    data}, this.onEndReceiveDataDelegate, this.onReceiveDataCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IReceiveData.BeginReceivePoint(System.TupleOfdoubledoubledouble data, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginReceivePoint(data, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IReceiveData.EndReceivePoint(System.IAsyncResult result)
    {
        base.Channel.EndReceivePoint(result);
    }
    
    private System.IAsyncResult OnBeginReceivePoint(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.TupleOfdoubledoubledouble data = ((System.TupleOfdoubledoubledouble)(inValues[0]));
        return ((IReceiveData)(this)).BeginReceivePoint(data, callback, asyncState);
    }
    
    private object[] OnEndReceivePoint(System.IAsyncResult result)
    {
        ((IReceiveData)(this)).EndReceivePoint(result);
        return null;
    }
    
    private void OnReceivePointCompleted(object state)
    {
        if ((this.ReceivePointCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ReceivePointCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ReceivePointAsync(System.TupleOfdoubledoubledouble data)
    {
        this.ReceivePointAsync(data, null);
    }
    
    public void ReceivePointAsync(System.TupleOfdoubledoubledouble data, object userState)
    {
        if ((this.onBeginReceivePointDelegate == null))
        {
            this.onBeginReceivePointDelegate = new BeginOperationDelegate(this.OnBeginReceivePoint);
        }
        if ((this.onEndReceivePointDelegate == null))
        {
            this.onEndReceivePointDelegate = new EndOperationDelegate(this.OnEndReceivePoint);
        }
        if ((this.onReceivePointCompletedDelegate == null))
        {
            this.onReceivePointCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceivePointCompleted);
        }
        base.InvokeAsync(this.onBeginReceivePointDelegate, new object[] {
                    data}, this.onEndReceivePointDelegate, this.onReceivePointCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IReceiveData.BeginReceivePoints(System.TupleOfdoubledoubledouble[] data, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginReceivePoints(data, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IReceiveData.EndReceivePoints(System.IAsyncResult result)
    {
        base.Channel.EndReceivePoints(result);
    }
    
    private System.IAsyncResult OnBeginReceivePoints(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.TupleOfdoubledoubledouble[] data = ((System.TupleOfdoubledoubledouble[])(inValues[0]));
        return ((IReceiveData)(this)).BeginReceivePoints(data, callback, asyncState);
    }
    
    private object[] OnEndReceivePoints(System.IAsyncResult result)
    {
        ((IReceiveData)(this)).EndReceivePoints(result);
        return null;
    }
    
    private void OnReceivePointsCompleted(object state)
    {
        if ((this.ReceivePointsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ReceivePointsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ReceivePointsAsync(System.TupleOfdoubledoubledouble[] data)
    {
        this.ReceivePointsAsync(data, null);
    }
    
    public void ReceivePointsAsync(System.TupleOfdoubledoubledouble[] data, object userState)
    {
        if ((this.onBeginReceivePointsDelegate == null))
        {
            this.onBeginReceivePointsDelegate = new BeginOperationDelegate(this.OnBeginReceivePoints);
        }
        if ((this.onEndReceivePointsDelegate == null))
        {
            this.onEndReceivePointsDelegate = new EndOperationDelegate(this.OnEndReceivePoints);
        }
        if ((this.onReceivePointsCompletedDelegate == null))
        {
            this.onReceivePointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceivePointsCompleted);
        }
        base.InvokeAsync(this.onBeginReceivePointsDelegate, new object[] {
                    data}, this.onEndReceivePointsDelegate, this.onReceivePointsCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IReceiveData CreateChannel()
    {
        return new ReceiveDataClientChannel(this);
    }
    
    private class ReceiveDataClientChannel : ChannelBase<IReceiveData>, IReceiveData
    {
        
        public ReceiveDataClientChannel(System.ServiceModel.ClientBase<IReceiveData> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginReceiveData(byte[] data, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = data;
            System.IAsyncResult _result = base.BeginInvoke("ReceiveData", _args, callback, asyncState);
            return _result;
        }
        
        public void EndReceiveData(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("ReceiveData", _args, result);
        }
        
        public System.IAsyncResult BeginReceivePoint(System.TupleOfdoubledoubledouble data, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = data;
            System.IAsyncResult _result = base.BeginInvoke("ReceivePoint", _args, callback, asyncState);
            return _result;
        }
        
        public void EndReceivePoint(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("ReceivePoint", _args, result);
        }
        
        public System.IAsyncResult BeginReceivePoints(System.TupleOfdoubledoubledouble[] data, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = data;
            System.IAsyncResult _result = base.BeginInvoke("ReceivePoints", _args, callback, asyncState);
            return _result;
        }
        
        public void EndReceivePoints(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("ReceivePoints", _args, result);
        }
    }
}
