
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace global
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException390abdc8086f4b12b99983f4182c3482 of obj
    exception ReturnNoneException390abdc8086f4b12b99983f4182c3482
    [<AutoOpen>]
    module FuncConvertFinalOverload390abdc8086f4b12b99983f4182c3482 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0");
          System.ServiceModel.ServiceContractAttribute(ConfigurationName="IReceiveData")>]
        IReceiveData = interface
            
            abstract EndReceiveData : System.IAsyncResult -> unit
            
            [<System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReceiveData/ReceiveData", ReplyAction="http://tempuri.org/IReceiveData/ReceiveDataResponse")>]
            abstract BeginReceiveData : System.Byte[] * System.AsyncCallback * obj -> System.IAsyncResult
        end
    
    and
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>]
        IReceiveDataChannel = interface
            inherit IReceiveData
            
            inherit System.ServiceModel.IClientChannel
            
        end